# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-06-04 08:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0003_auto_20150527_1555'),
        ('sites', '0002_alter_domain_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('leader_text', models.TextField(blank=True, help_text=b'Add <br> for line breaks')),
                ('button_text', models.CharField(blank=True, help_text=b'Optional, if present a button with the link specified below will be in the slide', max_length=100)),
                ('button_link', models.CharField(blank=True, max_length=2000)),
                ('icon_box_layout', models.CharField(choices=[(b'TW', b'Two across'), (b'TH', b'Three across'), (b'TB', b'Three across boxes')], default=b'TH', max_length=2)),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Home page',
                'verbose_name_plural': 'Home pages',
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='IconBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('icon', models.CharField(help_text=b'Enter the name of a font awesome icon, i.e. fa-eye. A list is available here http://fontawesome.io/', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('content', mezzanine.core.fields.RichTextField()),
                ('link', models.CharField(blank=True, help_text=b'Optional, if provided clicking the box will go here.', max_length=2000)),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='boxes', to='apptheme_mezzanine.HomePage')),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', mezzanine.core.fields.FileField(blank=True, max_length=200, verbose_name='File')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('job_title', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('bio', mezzanine.core.fields.RichTextField(blank=True, help_text=b'brief bio of person')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'persons',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('leader', models.CharField(blank=True, help_text=b'Optional brief intro.', max_length=4096)),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Portfolio',
                'verbose_name_plural': 'Portfolios',
            },
            bases=('pages.page',),
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='pages.Page')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('leader', models.CharField(blank=True, help_text=b'leader text for display in parent portfolio', max_length=200)),
                ('intro', mezzanine.core.fields.RichTextField(blank=True, help_text=b'brief intro paragraph used for leader')),
                ('icon', models.CharField(blank=True, help_text=b'Enter the name of a font awesome icon, i.e. fa-eye. A list is available here http://fontawesome.io/', max_length=50)),
                ('href', models.CharField(blank=True, help_text=b'A link to the finished project (optional)', max_length=2000)),
                ('button_text', models.CharField(blank=True, help_text=b"Optional, if present the default 'Learn More' text on the button will be replaced with the text provided", max_length=100)),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Portfolio item',
                'verbose_name_plural': 'Portfolio items',
            },
            bases=('pages.page', models.Model),
        ),
        migrations.CreateModel(
            name='PortfolioItemCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, null=True, verbose_name='URL')),
                ('site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'ordering': ('title',),
                'verbose_name': 'Portfolio Item Category',
                'verbose_name_plural': 'Portfolio Item Categories',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItemImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('file', mezzanine.core.fields.FileField(max_length=200, verbose_name='File')),
                ('alt_text', models.CharField(blank=True, max_length=200)),
                ('is_logo', models.BooleanField(default=False, help_text=b'Is this image THE logo for the item?')),
                ('portfolioitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='apptheme_mezzanine.PortfolioItem')),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.CreateModel(
            name='PortfolioItemPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptheme_mezzanine.Person')),
                ('portfolioitem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='persons', to='apptheme_mezzanine.PortfolioItem')),
            ],
            options={
                'ordering': ('_order',),
                'verbose_name': 'Associated person',
                'verbose_name_plural': 'Associated people',
            },
        ),
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_order', mezzanine.core.fields.OrderField(null=True, verbose_name='Order')),
                ('heading', models.CharField(blank=True, max_length=100)),
                ('subheading', models.CharField(blank=True, max_length=100)),
                ('credit', models.CharField(blank=True, help_text=b'credit for slide image', max_length=100)),
                ('button_text', models.CharField(blank=True, help_text=b'Optional, if present a button with the link specified below will be in the slide', max_length=100)),
                ('button_link', models.CharField(blank=True, max_length=2000)),
                ('image', mezzanine.core.fields.FileField(blank=True, max_length=255, verbose_name='Image')),
                ('custom', models.TextField(blank=True, help_text=b'Create a custom slide, everything else will be overriden')),
                ('homepage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slides', to='apptheme_mezzanine.HomePage')),
            ],
            options={
                'ordering': ('_order',),
            },
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='portfolioitems', to='apptheme_mezzanine.PortfolioItemCategory', verbose_name='Categories'),
        ),
    ]
