# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2019-02-05 18:51
from __future__ import unicode_literals

from django.db import migrations
import mezzanine.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('apptheme_mezzanine', '0002_auto_20190201_2224'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='leader',
        ),
        migrations.AddField(
            model_name='portfolio',
            name='content',
            field=mezzanine.core.fields.RichTextField(blank=True, help_text=b'Brief introduction to Portfolio'),
        ),
    ]
